services:
  db:
    image: postgres:latest
    environment:
      POSTGRES+DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./local_data:/app/local_data # Monta dados locais do host para o contêiner
volumes:
  postgres_data:
